// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReactHooks = require("@testing-library/react-hooks");

var Result = /* module */[];

var Options = /* module */[];

function act(callback) {
  ReactHooks.act((function () {
          Curry._1(callback, /* () */0);
          return undefined;
        }));
  return /* () */0;
}

exports.Result = Result;
exports.Options = Options;
exports.act = act;
/* @testing-library/react-hooks Not a pure module */
