// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var Result = /* module */[];

var Options = /* module */[];

exports.Result = Result;
exports.Options = Options;
/* No side effect */
